apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-qyet
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-tmcx-tenant/rhtap-demo-app/hacbs-test-project-qyet@sha256:f8e326498e1aedac94b8bd0bc9b15fbfe145ec99858255c66dc2e9f1731c3a25
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
